export interface ComplianceRule {
  id: string;
  phrase: string;
  riskScore: number;
  category:
    | "Off-Platform Communication"
    | "External Payments"
    | "Fiverr Fee Circumvention"
    | "Personal Contact Information"
    | "Phishing & Suspicious Language"
    | "Academic Integrity Violations"
    | "Feedback & Review Manipulation"
    | "Harassment & Unprofessional"
    | "Prohibited & Illegal Services"
    | "Employment & Recruitment Off-Platform"
    | "Off-Platform Transactions & Finance";
  severity: "Low Risk" | "Medium Risk" | "High Risk" | "Critical Risk";
  pattern: string;
  rewrite: string;
  explanation: string;
}

export const complianceDatabase: ComplianceRule[] = [
  {
    id: "tos_001",
    phrase: "whatsapp",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bwhatsapp\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_002",
    phrase: "telegram",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\btelegram\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_003",
    phrase: "discord",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bdiscord\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_004",
    phrase: "skype",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bskype\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_005",
    phrase: "slack",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bslack\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_006",
    phrase: "viber",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bviber\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_007",
    phrase: "wechat",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bwechat\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_008",
    phrase: "facebook",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bfacebook\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_009",
    phrase: "instagram",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\binstagram\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_010",
    phrase: "linkedin",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\blinkedin\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Social/chat app.",
  },
  {
    id: "tos_011",
    phrase: "email",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bemail\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_012",
    phrase: "mail",
    riskScore: 90,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bmail\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_013",
    phrase: "phone number",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bphone number\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_014",
    phrase: "cell",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bcell\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_015",
    phrase: "mobile",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bmobile\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_016",
    phrase: "digits",
    riskScore: 90,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bdigits\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_017",
    phrase: "address",
    riskScore: 90,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\baddress\\b",
    rewrite: "the Fiverr workspace",
    explanation: "Contact detail.",
  },
  {
    id: "tos_018",
    phrase: "zoom",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bzoom\\b",
    rewrite: "the Fiverr native call",
    explanation: "Meeting platform.",
  },
  {
    id: "tos_019",
    phrase: "google meet",
    riskScore: 95,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bgoogle meet\\b",
    rewrite: "the Fiverr native call",
    explanation: "Meeting platform.",
  },
  {
    id: "tos_020",
    phrase: "teams",
    riskScore: 90,
    category: "Off-Platform Communication" as any,
    severity: "High Risk" as any,
    pattern: "\\bteams\\b",
    rewrite: "the Fiverr native call",
    explanation: "Meeting platform.",
  },
  {
    id: "tos_021",
    phrase: "outside of fiverr",
    riskScore: 100,
    category: "Off-Platform Communication" as any,
    severity: "Critical Risk" as any,
    pattern: "\\boutside of fiverr\\b",
    rewrite: "here on Fiverr",
    explanation: "The ultimate trap phrase.",
  },
  {
    id: "tos_022",
    phrase: "off-platform",
    riskScore: 100,
    category: "Off-Platform Communication" as any,
    severity: "Critical Risk" as any,
    pattern: "\\boff-platform\\b",
    rewrite: "here on Fiverr",
    explanation: "The ultimate trap phrase.",
  },
  {
    id: "tos_023",
    phrase: "paypal",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bpaypal\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_024",
    phrase: "stripe",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bstripe\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_025",
    phrase: "payoneer",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bpayoneer\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_026",
    phrase: "wise",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bwise\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_027",
    phrase: "transferwise",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\btransferwise\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_028",
    phrase: "western union",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bwestern union\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_029",
    phrase: "bank transfer",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bbank transfer\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_030",
    phrase: "cash",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bcash\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_031",
    phrase: "crypto",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bcrypto\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_032",
    phrase: "bitcoin",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bbitcoin\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_033",
    phrase: "usdt",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\busdt\\b",
    rewrite: "the Fiverr order page",
    explanation: "Payment service.",
  },
  {
    id: "tos_034",
    phrase: "pay",
    riskScore: 90,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "High Risk" as any,
    pattern: "\\bpay\\b",
    rewrite: "order",
    explanation: "Financial action.",
  },
  {
    id: "tos_035",
    phrase: "payment",
    riskScore: 90,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "High Risk" as any,
    pattern: "\\bpayment\\b",
    rewrite: "order",
    explanation: "Financial action.",
  },
  {
    id: "tos_036",
    phrase: "invoice",
    riskScore: 90,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "High Risk" as any,
    pattern: "\\binvoice\\b",
    rewrite: "custom offer",
    explanation: "Financial action.",
  },
  {
    id: "tos_037",
    phrase: "send money",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bsend money\\b",
    rewrite: "place an order",
    explanation: "Financial action.",
  },
  {
    id: "tos_038",
    phrase: "direct deposit",
    riskScore: 100,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bdirect deposit\\b",
    rewrite: "Fiverr payment",
    explanation: "Financial action.",
  },
  {
    id: "tos_039",
    phrase: "fee",
    riskScore: 85,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "High Risk" as any,
    pattern: "\\bfee\\b",
    rewrite: "budget",
    explanation: "Financial action.",
  },
  {
    id: "tos_040",
    phrase: "commission",
    riskScore: 85,
    category: "Off-Platform Transactions & Finance" as any,
    severity: "High Risk" as any,
    pattern: "\\bcommission\\b",
    rewrite: "price",
    explanation: "Financial action.",
  },
  {
    id: "tos_041",
    phrase: "homework",
    riskScore: 100,
    category: "Academic Integrity Violations" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bhomework\\b",
    rewrite: "study guide",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_042",
    phrase: "assignment",
    riskScore: 95,
    category: "Academic Integrity Violations" as any,
    severity: "High Risk" as any,
    pattern: "\\bassignment\\b",
    rewrite: "project",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_043",
    phrase: "exam",
    riskScore: 100,
    category: "Academic Integrity Violations" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bexam\\b",
    rewrite: "prep materials",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_044",
    phrase: "test",
    riskScore: 90,
    category: "Academic Integrity Violations" as any,
    severity: "High Risk" as any,
    pattern: "\\btest\\b",
    rewrite: "review sheet",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_045",
    phrase: "quiz",
    riskScore: 90,
    category: "Academic Integrity Violations" as any,
    severity: "High Risk" as any,
    pattern: "\\bquiz\\b",
    rewrite: "practice questions",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_046",
    phrase: "university project",
    riskScore: 100,
    category: "Academic Integrity Violations" as any,
    severity: "Critical Risk" as any,
    pattern: "\\buniversity project\\b",
    rewrite: "personal project",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_047",
    phrase: "academic paper",
    riskScore: 100,
    category: "Academic Integrity Violations" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bacademic paper\\b",
    rewrite: "research summary",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_048",
    phrase: "thesis",
    riskScore: 100,
    category: "Academic Integrity Violations" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bthesis\\b",
    rewrite: "research outline",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_049",
    phrase: "dissertation",
    riskScore: 100,
    category: "Academic Integrity Violations" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bdissertation\\b",
    rewrite: "independent study",
    explanation: "Academic dishonesty.",
  },
  {
    id: "tos_050",
    phrase: "review",
    riskScore: 95,
    category: "Feedback & Review Manipulation" as any,
    severity: "High Risk" as any,
    pattern: "\\breview\\b",
    rewrite: "honest feedback",
    explanation: "Review manipulation.",
  },
  {
    id: "tos_051",
    phrase: "5 stars",
    riskScore: 95,
    category: "Feedback & Review Manipulation" as any,
    severity: "High Risk" as any,
    pattern: "\\b5 stars\\b",
    rewrite: "honest feedback",
    explanation: "Review manipulation.",
  },
  {
    id: "tos_052",
    phrase: "five stars",
    riskScore: 95,
    category: "Feedback & Review Manipulation" as any,
    severity: "High Risk" as any,
    pattern: "\\bfive stars\\b",
    rewrite: "honest feedback",
    explanation: "Review manipulation.",
  },
  {
    id: "tos_053",
    phrase: "positive review",
    riskScore: 95,
    category: "Feedback & Review Manipulation" as any,
    severity: "High Risk" as any,
    pattern: "\\bpositive review\\b",
    rewrite: "honest feedback",
    explanation: "Review manipulation.",
  },
  {
    id: "tos_054",
    phrase: "feedback",
    riskScore: 70,
    category: "Feedback & Review Manipulation" as any,
    severity: "Medium Risk" as any,
    pattern: "\\bfeedback\\b",
    rewrite: "thoughts",
    explanation: "Review manipulation context.",
  },
  {
    id: "tos_055",
    phrase: "rating",
    riskScore: 85,
    category: "Feedback & Review Manipulation" as any,
    severity: "High Risk" as any,
    pattern: "\\brating\\b",
    rewrite: "experience",
    explanation: "Review manipulation.",
  },
  {
    id: "tos_056",
    phrase: "thumbs up",
    riskScore: 85,
    category: "Feedback & Review Manipulation" as any,
    severity: "High Risk" as any,
    pattern: "\\bthumbs up\\b",
    rewrite: "approval",
    explanation: "Review manipulation.",
  },
  {
    id: "tos_057",
    phrase: "scrape",
    riskScore: 90,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "High Risk" as any,
    pattern: "\\bscrape\\b",
    rewrite: "gather public data",
    explanation: "Growth exploit.",
  },
  {
    id: "tos_058",
    phrase: "bot",
    riskScore: 90,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "High Risk" as any,
    pattern: "\\bbot\\b",
    rewrite: "automation script",
    explanation: "Growth exploit.",
  },
  {
    id: "tos_059",
    phrase: "fake followers",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bfake followers\\b",
    rewrite: "organic marketing strategy",
    explanation: "Growth exploit.",
  },
  {
    id: "tos_060",
    phrase: "bulk emails",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bbulk emails\\b",
    rewrite: "newsletter management",
    explanation: "Growth exploit.",
  },
  {
    id: "tos_061",
    phrase: "spam",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bspam\\b",
    rewrite: "outreach",
    explanation: "Growth exploit.",
  },
  {
    id: "tos_062",
    phrase: "create accounts",
    riskScore: 95,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "High Risk" as any,
    pattern: "\\bcreate accounts\\b",
    rewrite: "manage your account",
    explanation: "Growth exploit.",
  },
  {
    id: "tos_063",
    phrase: "adult",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\badult\\b",
    rewrite: "general",
    explanation: "Adult/Sensitive Content.",
  },
  {
    id: "tos_064",
    phrase: "nsfw",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bnsfw\\b",
    rewrite: "safe for work",
    explanation: "Adult/Sensitive Content.",
  },
  {
    id: "tos_065",
    phrase: "dating",
    riskScore: 90,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "High Risk" as any,
    pattern: "\\bdating\\b",
    rewrite: "networking",
    explanation: "Adult/Sensitive Content.",
  },
  {
    id: "tos_066",
    phrase: "nude",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bnude\\b",
    rewrite: "appropriate",
    explanation: "Adult/Sensitive Content.",
  },
  {
    id: "tos_067",
    phrase: "sexy",
    riskScore: 100,
    category: "Prohibited Services & High-Risk Content" as any,
    severity: "Critical Risk" as any,
    pattern: "\\bsexy\\b",
    rewrite: "appealing",
    explanation: "Adult/Sensitive Content.",
  },
];

export const fullComplianceDatabase: ComplianceRule[] = [...complianceDatabase];
